In [2]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scipy.stats as stats
import seaborn as sns

In [6]:
three_rt = pd.read_csv("C:\\Users\\jhonm\\Desktop\\Code\\Python\\SFLP\\data\\_inputfiles\\03_RT.csv", sep="\t")
three_rt

          CASE        RT  FREQ  FAM  IMA   MEAN
0       almond  650.9947     2  NaN  NaN    NaN
1          ant  589.4347     7  med   hi  415.0
2        apple  523.0493    10   hi   hi  451.0
3      apricot  642.3342     2   lo   lo    NaN
4    asparagus  696.2092     2  med   lo  442.0
..         ...       ...   ...  ...  ...    ...
72    tortoise  733.0323     4   lo   lo  403.0
73      walnut  663.5908    12  med   lo  468.0
74        wasp  725.7056     3  NaN  NaN    NaN
75       whale  609.9745     1  med   hi  474.0
76  woodpecker  686.3439     2  NaN  NaN    NaN

[77 rows x 6 columns]

In [7]:
three_rt.describe()

               RT        FREQ        MEAN
count   77.000000   77.000000   48.000000
mean   631.859958    9.259740  435.979167
std     60.163206   16.993344   43.243738
min    523.049300    1.000000  315.000000
25%    589.434700    2.000000  409.750000
50%    617.736700    4.000000  437.500000
75%    663.590800   10.000000  466.250000
max    794.452200  118.000000  553.000000